---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/dev/test1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---