---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-ingress
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/dev/traefik-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---