---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-traefik-ingress-static
  namespace: ns-traefik-ingress
  labels:
    app: traefik-ingress
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entryPoints:
      http:
        address: :80
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
              permanent: false
              priority: 1
      https:
        address: :443
        http:
          tls: {}
    providers:
      kubernetesCRD: {}
    api:
      dashboard: true
    ping:
      entryPoint: http
    log:
      level: INFO
    certificatesResolvers:
      default:
        acme:
          email: sinder.grindvoll@amesto.no
          storage: /acme/acme.json
          tlsChallenge: {}