---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress
  namespace: ns-traefik-ingress
  labels:
    app: traefik-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: traefik-ingress
    spec:
      serviceAccountName: sa-traefik
      containers:
        - image: traefik:3.0
          imagePullPolicy: IfNotPresent
          name: traefik-ingress
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 500m
          securityContext:
            capabilities:
              add:
                - NET_BIND_ERVICE
              drop:
                - ALL
          volumeMounts:
            - mountPath: /acme
              name: acme
            - mountPath: /etc/traefik/traefik.yaml
              name: config-static
              subPath: traefik.yml
      volumes:
        - name: acme
          persistentVolumeClaim:
            claimName: pvc-nfs-traefik-ingress
        - name: config-static
          configMap:
            name: cm-traefik-ingress-static