---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-traefik-ingress
  namespace: ns-traefik-ingress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10M
  storageClassName: ''
  volumeName: nfs-traefik-ingress
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-traefik-ingress
spec:
  capacity:
    storage: 10M
  claimRef:
    name: pvc-nfs-traefik-ingress
    namespace: ns-traefik-ingress
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ''
  nfs:
    server: 127.0.0.1
    path: /