---
apiVersion: v1
kind: Service
metadata:
  name: svc-traefik-ingress
  namespace: ns-traefik-ingress
spec:
  externalTrafficPolicy: Local
  selector:
    app: traefik-ingress
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  type: LoadBalancer
  loadBalancerIp: 127.0.0.1