---
apiVersion: v1
kind: Service
metadata:
  name: svc-traefik-dashboard
  namespace: ns-traefik-ingress

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: svc-traefik-web
  namespace: ns-traefik-ingress

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik-ingress
