---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-whoami
  namespace: ns-whoami

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-whoami
                port:
                  name: web